### ISSUE TITLE
Verify support for Python 3

### ISSUE THREAD

**Issue by lukacu** [votchallenge/trax#37]
Python 3 support was never tested, we have to make sure that it works.

**Comment by cc786537662** [comment]
I am pretty sure that python 3 is not working now ,this only works fine with python 2,while python2 works fine,when i switch to python 3,error comes like:
Loading sequences ...
Testing TraX protocol support for tracker v1.
Tracker execution interrupted: Unable to establish connection.
TraX support not detected.

**Comment by lukacu** [comment]
Well, the idea of this issue is that we determine the changes in the code to get it working in Python 3. Simply testing the tracker in VOT toolkit will not be really useful unless you also past the error from the log file.

**Comment by i-lovelife** [comment]
I just have made it pass the run_test in python3, there are two positions need to be modified:
1.xrange. just `grep -nr 'xrange'` and find the correspond position and replace it with `range`, since python3 merge range and xrange
2.map. I only find in python/trax/region.py:70,replace `tokens = map(float, string.split(','))` to `tokens = list(map(float, string.split(',')))`

**Comment by alanlukezic** [comment]
Great, thank you! We will include this fix in the future versions of the toolkit.

**Comment by lukacu** [comment]
Added to master.
